---
name: "SRT Reservation System"
version: "1.0.0"
slug: "srt_reservation"
description: "SRT 예약 시스템"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/jinizest/SuperT
startup: application
boot: auto
uart: true
map:
  - share:rw
webui: "http://[HOST]:[PORT:5000]"
options:
  SRT_ID: ""
  SRT_PASSWORD: ""
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHAT_ID: ""
  PHONE_NUMBER: ""
schema:
  SRT_ID: str
  SRT_PASSWORD: password
  TELEGRAM_BOT_TOKEN: str?
  TELEGRAM_CHAT_ID: str?
  PHONE_NUMBER:
    name: "휴대폰 번호"
    description: "휴대폰 번호를 입력하세요 (예: 010-1234-5678)"
    type: str?
ports:
  5000/tcp: 5000
