name: "SRT Reservation System"
version: "1.0.0"
slug: "srt_reservation"
description: "SRT 예약 시스템"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  srt_id: ""
  srt_pw: ""
schema:
  srt_id: str
  srt_pw: str